apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-java-spring-docker

commonLabels:
  app.kubernetes.io/name: demo-java-spring-docker
  app.kubernetes.io/part-of: springdocker

resources:
  - deployment.yaml
  - service.yaml
