from __future__ import annotations

import re
from dataclasses import dataclass


@dataclass(frozen=True)
class DockerfileOptions:
    build_tool: str
    java_version: int = 25
    use_buildkit_cache: bool = True
    use_jlink: bool = True
    non_root: bool = True
    tuned_jvm_flags: bool = True
    must_have_modules: tuple[str, ...] = ()
    runtime_image: str = "temurin"
    platform_aware: bool = True
    healthcheck_path: str | None = None
    include_oci_labels: bool = True
    include_stopsignal: bool = True


@dataclass(frozen=True)
class DockerfileSection:
    lines: tuple[str, ...]


@dataclass(frozen=True)
class DockerfileDocument:
    sections: tuple[DockerfileSection, ...]

    def render(self) -> str:
        lines: list[str] = []
        for section in self.sections:
            lines.extend(section.lines)
        return "\n".join(lines)


def _build_setup(build_tool: str) -> tuple[list[str], str, str]:
    if build_tool == "maven":
        return (
            [
                "COPY mvnw pom.xml ./",
                "COPY .mvn ./.mvn",
                "RUN chmod +x mvnw",
                "COPY src ./src",
            ],
            "./mvnw -B -q package -DskipTests",
            "target/*.jar",
        )
    return (
        [
            "COPY gradlew build.gradle settings.gradle ./",
            "COPY gradle ./gradle",
            "RUN chmod +x gradlew",
            "COPY src ./src",
        ],
        "./gradlew --no-daemon bootJar -x test",
        "build/libs/*-SNAPSHOT.jar",
    )


def _section(*lines: str) -> DockerfileSection:
    return DockerfileSection(lines=tuple(lines))


def _validate_options(options: DockerfileOptions) -> None:
    if options.build_tool not in {"maven", "gradle"}:
        raise ValueError("build tool must be 'maven' or 'gradle'")
    if options.java_version < 17:
        raise ValueError("java version must be >= 17")
    if options.runtime_image not in {"temurin", "distroless"}:
        raise ValueError("runtime_image must be 'temurin' or 'distroless'")


def _compose_dockerfile(options: DockerfileOptions) -> DockerfileDocument:
    setup, build_cmd, jar_path = _build_setup(options.build_tool)
    build_step = (
        "RUN --mount=type=cache,sharing=locked,target=/root/.m2 " + build_cmd
        if options.use_buildkit_cache and options.build_tool == "maven"
        else "RUN --mount=type=cache,sharing=locked,target=/root/.gradle " + build_cmd
        if options.use_buildkit_cache and options.build_tool == "gradle"
        else f"RUN {build_cmd}"
    )

    jvm_args: list[str] = []
    if options.tuned_jvm_flags:
        jvm_args.extend(
            [
                "-XX:MaxRAMPercentage=75",
                "-XX:+ExitOnOutOfMemoryError",
                "-Djava.io.tmpdir=/tmp",
            ]
        )

    sections: list[DockerfileSection] = [
        _section(
            "# syntax=docker/dockerfile:1",
            "# Generated by springdocker",
            f"# Java {options.java_version} | build-tool: {options.build_tool}",
            "",
        )
    ]
    if options.platform_aware:
        sections.append(_section("ARG TARGETPLATFORM", "ARG BUILDPLATFORM", ""))
    if options.include_oci_labels:
        sections.append(_section('ARG OCI_SOURCE=""', 'ARG OCI_REVISION=""', 'ARG OCI_CREATED=""', ""))
    sections.append(
        _section(
            f"FROM --platform=$BUILDPLATFORM eclipse-temurin:{options.java_version}-jdk AS build",
            "WORKDIR /app",
            *setup,
            build_step,
            "",
        )
    )

    if options.use_jlink:
        must_have_csv = ",".join(options.must_have_modules).replace('"', '\\"')
        sections.append(
            _section(
                f"FROM --platform=$BUILDPLATFORM eclipse-temurin:{options.java_version}-jdk AS jre-builder",
                "WORKDIR /jre",
                f"COPY --from=build /app/{jar_path} app.jar",
                (
                    f"RUN jdeps --ignore-missing-deps --recursive --multi-release {options.java_version} "
                    "--print-module-deps app.jar > modules.txt"
                ),
                f'ARG MUSTHAVE_MODULES="{must_have_csv}"',
                "RUN set -eux; \\",
                "    MODULES=$( (tr ',' '\\n' < modules.txt; printf '%s\\n' \"$MUSTHAVE_MODULES\" | tr ',' '\\n') \\",
                "      | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' | grep -v '^$' | sort -u | paste -sd, -); \\",
                "    jlink --add-modules \"$MODULES\" --strip-debug --no-man-pages --no-header-files --compress=2 --output /opt/java",
                "",
            )
        )

    if options.runtime_image == "distroless":
        runtime_base = (
            "gcr.io/distroless/base-debian12:nonroot"
            if options.use_jlink
            else f"gcr.io/distroless/java{options.java_version}-debian12:nonroot"
        )
        distroless_lines = [
            f"FROM --platform=$TARGETPLATFORM {runtime_base}",
            "WORKDIR /app",
            "VOLUME /tmp",
            f"COPY --from=build /app/{jar_path} app.jar",
            "EXPOSE 8080",
            "EXPOSE 8081",
        ]
        if options.include_oci_labels:
            distroless_lines.extend(
                [
                    'LABEL org.opencontainers.image.source="${OCI_SOURCE}" \\',
                    '      org.opencontainers.image.revision="${OCI_REVISION}" \\',
                    '      org.opencontainers.image.created="${OCI_CREATED}"',
                ]
            )
        if options.use_jlink:
            distroless_lines.extend(
                [
                    "COPY --from=jre-builder /opt/java /opt/java",
                    "ENV JAVA_HOME=/opt/java",
                    'ENV PATH="${JAVA_HOME}/bin:${PATH}"',
                ]
            )
        if options.non_root:
            distroless_lines.append("USER nonroot")
        sections.append(_section(*distroless_lines))
    else:
        temurin_lines = [f"FROM --platform=$TARGETPLATFORM eclipse-temurin:{options.java_version}-jre"]
        if options.non_root:
            temurin_lines.extend(
                [
                    "RUN groupadd --system --gid 1001 javauser && useradd --system --uid 1001 --gid 1001 --no-create-home --shell /usr/sbin/nologin javauser",
                    "RUN install -d -o 1001 -g 1001 -m 755 /app && install -d -o 1001 -g 1001 -m 1777 /tmp",
                ]
            )
        else:
            temurin_lines.append("RUN install -d -m 755 /app && install -d -m 1777 /tmp")

        temurin_lines.extend(
            [
                "WORKDIR /app",
                "VOLUME /tmp",
                f"COPY --from=build {'--chown=1001:1001 ' if options.non_root else ''}/app/{jar_path} app.jar",
                "EXPOSE 8080",
                "EXPOSE 8081",
            ]
        )
        if options.include_oci_labels:
            temurin_lines.extend(
                [
                    'LABEL org.opencontainers.image.source="${OCI_SOURCE}" \\',
                    '      org.opencontainers.image.revision="${OCI_REVISION}" \\',
                    '      org.opencontainers.image.created="${OCI_CREATED}"',
                ]
            )
        if options.healthcheck_path:
            temurin_lines.append(
                'HEALTHCHECK --interval=15s --timeout=3s --start-period=20s --retries=3 CMD wget -qO- "http://localhost:8080'
                + options.healthcheck_path
                + '" >/dev/null || exit 1'
            )
        sections.append(_section(*temurin_lines))

    if options.use_jlink and options.runtime_image != "distroless":
        sections.append(
            _section(
                "COPY --from=jre-builder /opt/java /opt/java",
                "ENV JAVA_HOME=/opt/java",
                'ENV PATH="${JAVA_HOME}/bin:${PATH}"',
            )
        )

    entrypoint = ["java", *jvm_args, "-jar", "app.jar"]
    tail_lines: list[str] = []
    if options.non_root and options.runtime_image != "distroless":
        tail_lines.append("USER 1001")
    if options.include_stopsignal:
        tail_lines.append("STOPSIGNAL SIGTERM")
    tail_lines.append("ENTRYPOINT [" + ", ".join(f'"{arg}"' for arg in entrypoint) + "]")
    tail_lines.append(
        "# Runtime hardening tip: run with --read-only --cap-drop=ALL --security-opt=no-new-privileges --tmpfs /tmp"
    )
    tail_lines.append("")
    sections.append(_section(*tail_lines))
    return DockerfileDocument(sections=tuple(sections))


def build_dockerfile(options: DockerfileOptions) -> str:
    _validate_options(options)
    return _compose_dockerfile(options).render()


def explain_dockerfile_text(text: str) -> dict[str, object]:
    lines = text.splitlines()
    if "# Generated by springdocker" not in text:
        raise ValueError("Dockerfile was not generated by springdocker")

    header_match = re.search(r"# Java (\d+) \| build-tool: (maven|gradle)", text)
    java_version = int(header_match.group(1)) if header_match else None
    build_tool = header_match.group(2) if header_match else None

    features: list[dict[str, object]] = []
    if sum(1 for line in lines if line.startswith("FROM ")) >= 2:
        features.append(
            {
                "name": "multi-stage build",
                "enabled": True,
                "reason": "Separates the build stage from the runtime stage.",
            }
        )
    if "jdeps" in text and "jlink" in text:
        features.append(
            {
                "name": "jlink runtime",
                "enabled": True,
                "reason": "Builds a smaller custom runtime from the detected module list.",
            }
        )
    if "--mount=type=cache" in text:
        features.append(
            {
                "name": "BuildKit cache",
                "enabled": True,
                "reason": "Caches Maven or Gradle dependencies between builds.",
            }
        )
    if "TARGETPLATFORM" in text and "BUILDPLATFORM" in text:
        features.append(
            {
                "name": "multi-architecture build",
                "enabled": True,
                "reason": "Uses Buildx platform arguments for arm64 and amd64 builds.",
            }
        )
    if "gcr.io/distroless" in text:
        features.append(
            {
                "name": "distroless runtime",
                "enabled": True,
                "reason": "Uses a minimal distroless runtime image.",
            }
        )
    if "VOLUME /tmp" in text:
        features.append(
            {
                "name": "read-only filesystem ready",
                "enabled": True,
                "reason": "Keeps /tmp writable when the container root filesystem is read-only.",
            }
        )
    if "USER 1001" in text or "USER nonroot" in text or "gcr.io/distroless" in text:
        features.append(
            {
                "name": "non-root runtime",
                "enabled": True,
                "reason": "Runs the application as an unprivileged container user.",
            }
        )
    if "-XX:MaxRAMPercentage=75" in text:
        features.append(
            {
                "name": "tuned JVM flags",
                "enabled": True,
                "reason": "Applies container-friendly JVM memory and failure defaults.",
            }
        )

    must_have_match = re.search(r'ARG MUSTHAVE_MODULES="([^"]*)"', text)
    must_have_modules = tuple(
        module for module in (part.strip() for part in (must_have_match.group(1) if must_have_match else "").split(",")) if module
    )
    if must_have_modules:
        features.append(
            {
                "name": "must-have modules",
                "enabled": True,
                "reason": "Includes manually curated modules that jdeps cannot infer reliably.",
            }
        )

    summary_parts = []
    if build_tool and java_version is not None:
        summary_parts.append(f"This {build_tool} Dockerfile targets Java {java_version}.")
    if any(feature["name"] == "multi-stage build" for feature in features):
        summary_parts.append("It uses a multi-stage build to keep the runtime image separate from compilation.")
    if any(feature["name"] == "jlink runtime" for feature in features):
        summary_parts.append("It builds a custom runtime with jlink.")
    if any(feature["name"] == "non-root runtime" for feature in features):
        summary_parts.append("It runs as a non-root user.")
    if any(feature["name"] == "BuildKit cache" for feature in features):
        summary_parts.append("It uses BuildKit cache mounts to speed up repeat builds.")
    if any(feature["name"] == "multi-architecture build" for feature in features):
        summary_parts.append("It is Buildx-friendly for amd64 and arm64 image builds.")
    if any(feature["name"] == "read-only filesystem ready" for feature in features):
        summary_parts.append("It keeps /tmp writable for read-only root filesystem deployments.")
    if any(feature["name"] == "tuned JVM flags" for feature in features):
        summary_parts.append("It applies container-oriented JVM defaults.")
    if must_have_modules:
        summary_parts.append("It adds curated modules for reflection or dynamic-loading edge cases.")

    if not summary_parts:
        summary_parts.append("No recognized springdocker optimizations were detected.")

    notes = [
        "Only Dockerfiles generated by springdocker are supported in v1.",
        "Explanation is based on static text signals in the file.",
    ]
    if "HEALTHCHECK" in text:
        features.append(
            {
                "name": "container healthcheck",
                "enabled": True,
                "reason": "Defines a runtime health probe for orchestrators and local checks.",
            }
        )
    if "STOPSIGNAL SIGTERM" in text:
        features.append(
            {
                "name": "explicit stop signal",
                "enabled": True,
                "reason": "Sets explicit signal semantics for clean shutdown behavior.",
            }
        )
    if "org.opencontainers.image.source" in text:
        features.append(
            {
                "name": "OCI image labels",
                "enabled": True,
                "reason": "Includes standard OCI metadata labels for provenance and traceability.",
            }
        )

    return {
        "source": "springdocker-generated Dockerfile",
        "build_tool": build_tool,
        "java_version": java_version,
        "stage_count": sum(1 for line in lines if line.startswith("FROM ")),
        "features": features,
        "summary": " ".join(summary_parts),
        "notes": notes,
    }
