from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class DockerfileOptions:
    build_tool: str
    java_version: int = 25
    use_buildkit_cache: bool = True
    use_jlink: bool = True
    non_root: bool = True
    tuned_jvm_flags: bool = True
    must_have_modules: tuple[str, ...] = ()


def _build_setup(build_tool: str) -> tuple[list[str], str, str]:
    if build_tool == "maven":
        return (
            [
                "COPY mvnw pom.xml ./",
                "COPY .mvn ./.mvn",
                "RUN chmod +x mvnw",
                "COPY src ./src",
            ],
            "./mvnw -B -q package -DskipTests",
            "target/*.jar",
        )
    return (
        [
            "COPY gradlew build.gradle settings.gradle ./",
            "COPY gradle ./gradle",
            "RUN chmod +x gradlew",
            "COPY src ./src",
        ],
        "./gradlew --no-daemon bootJar -x test",
        "build/libs/*-SNAPSHOT.jar",
    )


def build_dockerfile(options: DockerfileOptions) -> str:
    if options.build_tool not in {"maven", "gradle"}:
        raise ValueError("build tool must be 'maven' or 'gradle'")
    if options.java_version < 17:
        raise ValueError("java version must be >= 17")

    setup, build_cmd, jar_path = _build_setup(options.build_tool)
    build_step = (
        "RUN --mount=type=cache,sharing=locked,target=/root/.m2 " + build_cmd
        if options.use_buildkit_cache and options.build_tool == "maven"
        else "RUN --mount=type=cache,sharing=locked,target=/root/.gradle " + build_cmd
        if options.use_buildkit_cache and options.build_tool == "gradle"
        else f"RUN {build_cmd}"
    )

    jvm_args = []
    if options.tuned_jvm_flags:
        jvm_args.extend(
            [
                "-XX:MaxRAMPercentage=75",
                "-XX:+ExitOnOutOfMemoryError",
                "-Djava.io.tmpdir=/tmp",
            ]
        )

    lines: list[str] = [
        "# syntax=docker/dockerfile:1",
        "# Generated by springdocker",
        f"# Java {options.java_version} | build-tool: {options.build_tool}",
        "",
        f"FROM eclipse-temurin:{options.java_version}-jdk AS build",
        "WORKDIR /app",
        *setup,
        build_step,
        "",
    ]

    if options.use_jlink:
        must_have_csv = ",".join(options.must_have_modules).replace('"', '\\"')
        lines.extend(
            [
                f"FROM eclipse-temurin:{options.java_version}-jdk AS jre-builder",
                "WORKDIR /jre",
                f"COPY --from=build /app/{jar_path} app.jar",
                (
                    f"RUN jdeps --ignore-missing-deps --recursive --multi-release {options.java_version} "
                    "--print-module-deps app.jar > modules.txt"
                ),
                f'ARG MUSTHAVE_MODULES="{must_have_csv}"',
                "RUN set -eux; \\",
                "    MODULES=$( (tr ',' '\\n' < modules.txt; printf '%s\\n' \"$MUSTHAVE_MODULES\" | tr ',' '\\n') \\",
                "      | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' | grep -v '^$' | sort -u | paste -sd, -); \\",
                "    jlink --add-modules \"$MODULES\" --strip-debug --no-man-pages --no-header-files --compress=2 --output /opt/java",
                "",
            ]
        )

    lines.append(f"FROM eclipse-temurin:{options.java_version}-jre")
    if options.non_root:
        lines.extend(
            [
                "RUN groupadd --system --gid 1001 javauser && useradd --system --uid 1001 --gid 1001 --no-create-home --shell /usr/sbin/nologin javauser",
                "RUN install -d -o 1001 -g 1001 -m 755 /app && install -d -o 1001 -g 1001 -m 1777 /tmp",
            ]
        )
    else:
        lines.append("RUN install -d -m 755 /app && install -d -m 1777 /tmp")

    lines.extend(
        [
            "WORKDIR /app",
            f"COPY --from=build {'--chown=1001:1001 ' if options.non_root else ''}/app/{jar_path} app.jar",
            "EXPOSE 8080",
            "EXPOSE 8081",
        ]
    )

    if options.use_jlink:
        lines.extend(
            [
                "COPY --from=jre-builder /opt/java /opt/java",
                "ENV JAVA_HOME=/opt/java",
                'ENV PATH="${JAVA_HOME}/bin:${PATH}"',
            ]
        )

    entrypoint = ["java", *jvm_args, "-jar", "app.jar"]
    if options.non_root:
        lines.append("USER 1001")
    lines.append("ENTRYPOINT [" + ", ".join(f'"{arg}"' for arg in entrypoint) + "]")
    lines.append("")
    return "\n".join(lines)
