from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class DockerfileOptions:
    build_tool: str
    java_version: int = 25
    use_buildkit_cache: bool = True
    use_jlink: bool = True
    non_root: bool = True
    healthcheck: bool = True
    tuned_jvm_flags: bool = True


def _build_setup(build_tool: str) -> tuple[list[str], str, str]:
    if build_tool == "maven":
        return (
            [
                "COPY mvnw pom.xml ./",
                "COPY .mvn ./.mvn",
                "RUN chmod +x mvnw",
                "COPY src ./src",
            ],
            "./mvnw -B -q package -DskipTests",
            "target/*.jar",
        )
    return (
        [
            "COPY gradlew build.gradle settings.gradle ./",
            "COPY gradle ./gradle",
            "RUN chmod +x gradlew",
            "COPY src ./src",
        ],
        "./gradlew --no-daemon bootJar -x test",
        "build/libs/*-SNAPSHOT.jar",
    )


def build_dockerfile(options: DockerfileOptions) -> str:
    if options.build_tool not in {"maven", "gradle"}:
        raise ValueError("build tool must be 'maven' or 'gradle'")
    if options.java_version < 17:
        raise ValueError("java version must be >= 17")

    setup, build_cmd, jar_path = _build_setup(options.build_tool)
    build_step = (
        "RUN --mount=type=cache,sharing=locked,target=/root/.m2 " + build_cmd
        if options.use_buildkit_cache and options.build_tool == "maven"
        else "RUN --mount=type=cache,sharing=locked,target=/root/.gradle " + build_cmd
        if options.use_buildkit_cache and options.build_tool == "gradle"
        else f"RUN {build_cmd}"
    )

    jvm_args = []
    if options.tuned_jvm_flags:
        jvm_args.extend(
            [
                "-XX:MaxRAMPercentage=75",
                "-XX:+ExitOnOutOfMemoryError",
                "-Djava.io.tmpdir=/tmp",
            ]
        )

    lines: list[str] = [
        "# syntax=docker/dockerfile:1",
        "# Generated by springdocker",
        f"# Java {options.java_version} | build-tool: {options.build_tool}",
        "",
        f"FROM eclipse-temurin:{options.java_version}-jdk AS build",
        "WORKDIR /app",
        *setup,
        build_step,
        "",
        f"FROM eclipse-temurin:{options.java_version}-jre",
        "RUN apt-get update && apt-get install -y --no-install-recommends curl && rm -rf /var/lib/apt/lists/*",
    ]
    if options.non_root:
        lines.extend(
            [
                "RUN groupadd --system --gid 1001 javauser && useradd --system --uid 1001 --gid 1001 --no-create-home --shell /usr/sbin/nologin javauser",
                "RUN install -d -o 1001 -g 1001 -m 755 /app && install -d -o 1001 -g 1001 -m 1777 /tmp",
            ]
        )
    else:
        lines.append("RUN install -d -m 755 /app && install -d -m 1777 /tmp")

    lines.extend(
        [
        "WORKDIR /app",
        f"COPY --from=build {'--chown=1001:1001 ' if options.non_root else ''}/app/{jar_path} app.jar",
        "EXPOSE 8080",
        "EXPOSE 8081",
        ]
    )

    if options.healthcheck:
        lines.extend(
            [
                "HEALTHCHECK --interval=30s --timeout=3s --start-period=60s --retries=3 \\",
                "  CMD curl -fsS http://localhost:8081/actuator/health/readiness || exit 1",
            ]
        )

    entrypoint = ["java", *jvm_args, "-jar", "app.jar"]
    if options.non_root:
        lines.append("USER 1001")
    lines.append("ENTRYPOINT [" + ", ".join(f'"{arg}"' for arg in entrypoint) + "]")
    lines.append("")
    return "\n".join(lines)
