# syntax=docker/dockerfile:1
# Generated by springdocker
# Java 21 | build-tool: gradle

ARG OCI_SOURCE=""
ARG OCI_REVISION=""
ARG OCI_CREATED=""

FROM --platform=$BUILDPLATFORM eclipse-temurin:21-jdk AS build
WORKDIR /app
COPY gradlew build.gradle settings.gradle ./
COPY gradle ./gradle
RUN chmod +x gradlew
COPY src ./src
RUN ./gradlew --no-daemon bootJar -x test

FROM --platform=$TARGETPLATFORM eclipse-temurin:21-jre
RUN install -d -m 755 /app && install -d -m 1777 /tmp
WORKDIR /app
VOLUME /tmp
COPY --from=build /app/build/libs/*-SNAPSHOT.jar app.jar
EXPOSE 8080
EXPOSE 8081
LABEL org.opencontainers.image.source="${OCI_SOURCE}" \
      org.opencontainers.image.revision="${OCI_REVISION}" \
      org.opencontainers.image.created="${OCI_CREATED}"
STOPSIGNAL SIGTERM
ENTRYPOINT ["java", "-jar", "app.jar"]
# Runtime hardening tip: run with --read-only --cap-drop=ALL --security-opt=no-new-privileges --tmpfs /tmp
