from __future__ import annotations

import unittest

from tests.test_support import add_src_to_path

add_src_to_path()

from springdocker.dockerfile import DockerfileOptions, build_dockerfile


class DockerfileTemplateRenderingTests(unittest.TestCase):
    def test_template_render_keeps_generated_header(self) -> None:
        rendered = build_dockerfile(DockerfileOptions(build_tool="maven", java_version=21))
        self.assertIn("# Generated by springdocker", rendered)
        self.assertIn("# Java 21 | build-tool: maven", rendered)


if __name__ == "__main__":
    unittest.main()
