apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-java-spring-docker
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: demo-java-spring-docker
  endpoints:
    - path: /actuator/prometheus
      port: management
      interval: 15s

